{
 "title": "VNX Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Array",
    "label": "Array S/N",
    "query": "SHOW TAG VALUES WITH KEY = \"S/N\" WHERE \"S/N\" =~ /[A-Z]/"
   }
  ]
 },
 "panels": [
  {
   "title": "Storage Processor % Busy",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "SP$tag_storage_processor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "storage_processor" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Array",
     "select": [
      [
       { "params": [ "percent_busy" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "S/N", "operator": "=~", "value": "/^$Array$/" }
     ]
    }
   ]
  },
  {
   "title": "Capacity Free",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "alias": "Pool $tag_pool_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pool_id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Pool",
     "select": [
      [
       { "params": [ "available_capacity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "S/N", "operator": "=~", "value": "/^$Array$/" }
     ]
    }
   ]
  },
  {
   "title": "Write Requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "SP$tag_storage_processor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "storage_processor" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Array",
     "select": [
      [
       { "params": [ "write_requests" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "S/N", "operator": "=~", "value": "/^$Array$/" }
     ]
    }
   ]
  },
  {
   "title": "Read Requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "SP$tag_storage_processor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "storage_processor" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Array",
     "select": [
      [
       { "params": [ "read_requests" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "S/N", "operator": "=~", "value": "/^$Array$/" }
     ]
    }
   ]
  },
  {
   "title": "Cache Read Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "SP$tag_storage_processor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "storage_processor" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Cache",
     "select": [
      [
       { "params": [ "read_hit_ratio" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "S/N", "operator": "=~", "value": "/^$Array$/" }
     ]
    }
   ]
  },
  {
   "title": "Cache Write Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "SP$tag_storage_processor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "storage_processor" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Cache",
     "select": [
      [
       { "params": [ "write_hit_ratio" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "S/N", "operator": "=~", "value": "/^$Array$/" }
     ]
    }
   ]
  },
  {
   "title": "Port Reads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Port $tag_port_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "port_id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "VNX Port",
     "select": [
      [
       { "params": [ "reads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "S/N", "operator": "=~", "value": "/^$Array$/" }
     ]
    }
   ]
  },
  {
   "title": "Port Writes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Port $tag_port_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "port_id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "VNX Port",
     "select": [
      [
       { "params": [ "writes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "S/N", "operator": "=~", "value": "/^$Array$/" }
     ]
    }
   ]
  }
 ]
}