{
 "title": "3Par Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "SELECT DISTINCT host FROM Volume"
   },
   {
    "name": "array",
    "label": "Array ID",
    "query": "SHOW TAG VALUES FROM Volume WITH KEY = \"S/N\""
   }
  ]
 },
 "panels": [
  { "title": "Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pool FC - Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Array",
     "select": [
      [
       { "params": [ "total_usable_cap_gb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "S/N", "operator": "=~", "value": "/^$array$/" },
      { "condition": "AND", "key": "disktype", "operator": "=", "value": "FC" }
     ]
    }
   ]
  },
  {
   "title": "Pool FC - Alocado",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Array",
     "select": [
      [
       { "params": [ "total_allocated_cap_gb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "S/N", "operator": "=~", "value": "/^$array$/" },
      { "condition": "AND", "key": "disktype", "operator": "=", "value": "FC" }
     ]
    }
   ]
  },
  {
   "title": "Pool FC - Escrito",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Array",
     "select": [
      [
       { "params": [ "total_subscribed_cap_gb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "S/N", "operator": "=~", "value": "/^$array$/" },
      { "condition": "AND", "key": "disktype", "operator": "=", "value": "FC" }
     ]
    }
   ]
  },
  {
   "title": "Pool FC - Livre",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Array",
     "query": "SELECT last(\"total_usable_cap_gb\") / 1024 - last(\"total_subscribed_cap_gb\" )  / 1024 FROM \"Array\" WHERE (\"S/N\" =~ /^$array$/ AND \"disktype\" = 'FC') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total_subscribed_cap_gb" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "S/N", "operator": "=~", "value": "/^$array$/" },
      { "condition": "AND", "key": "disktype", "operator": "=", "value": "FC" }
     ]
    }
   ]
  },
  {
   "title": "Pool SSD - Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Array",
     "select": [
      [
       { "params": [ "total_usable_cap_gb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "S/N", "operator": "=~", "value": "/^$array$/" },
      { "condition": "AND", "key": "disktype", "operator": "=", "value": "SSD" }
     ]
    }
   ]
  },
  {
   "title": "Pool SSD  - Alocado",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Array",
     "select": [
      [
       { "params": [ "total_allocated_cap_gb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "S/N", "operator": "=~", "value": "/^$array$/" },
      { "condition": "AND", "key": "disktype", "operator": "=", "value": "SSD" }
     ]
    }
   ]
  },
  {
   "title": "Pool SSD - Escrito",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Array",
     "select": [
      [
       { "params": [ "total_subscribed_cap_gb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "S/N", "operator": "=~", "value": "/^$array$/" },
      { "condition": "AND", "key": "disktype", "operator": "=", "value": "SSD" }
     ]
    }
   ]
  },
  {
   "title": "Pool FC - SSD",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Array",
     "query": "SELECT last(\"total_usable_cap_gb\") / 1024 - last(\"total_subscribed_cap_gb\" )  / 1024 FROM \"Array\" WHERE (\"S/N\" =~ /^$array$/ AND \"disktype\" = 'SSD') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total_subscribed_cap_gb" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "S/N", "operator": "=~", "value": "/^$array$/" },
      { "condition": "AND", "key": "disktype", "operator": "=", "value": "FC" }
     ]
    }
   ]
  },
  {
   "title": "Pool NL - Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "Array",
     "select": [
      [
       { "params": [ "total_usable_cap_gb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "S/N", "operator": "=~", "value": "/^$array$/" },
      { "condition": "AND", "key": "disktype", "operator": "=", "value": "NL" }
     ]
    }
   ]
  },
  {
   "title": "Pool NL- Alocado",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Array",
     "select": [
      [
       { "params": [ "total_allocated_cap_gb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "S/N", "operator": "=~", "value": "/^$array$/" },
      { "condition": "AND", "key": "disktype", "operator": "=", "value": "NL" }
     ]
    }
   ]
  },
  {
   "title": "Pool NL - Escrito",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Array",
     "select": [
      [
       { "params": [ "total_subscribed_cap_gb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "S/N", "operator": "=~", "value": "/^$array$/" },
      { "condition": "AND", "key": "disktype", "operator": "=", "value": "NL" }
     ]
    }
   ]
  },
  {
   "title": "Pool NL - Livre",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Array",
     "query": "SELECT last(\"total_usable_cap_gb\") / 1024 - last(\"total_subscribed_cap_gb\" )  / 1024 FROM \"Array\" WHERE (\"S/N\" =~ /^$array$/ AND \"disktype\" ='NL') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total_subscribed_cap_gb" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "S/N", "operator": "=~", "value": "/^$array$/" },
      { "condition": "AND", "key": "disktype", "operator": "=", "value": "FC" }
     ]
    }
   ]
  },
  { "title": "Port", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Port Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_port",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "port" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Port",
     "select": [
      [
       { "params": [ "busy" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "S/N", "operator": "=~", "value": "/^$array$/" }
     ]
    }
   ]
  },
  {
   "title": "Kb's Read",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_port",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "port" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Port",
     "select": [
      [
       { "params": [ "kb_read" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "S/N", "operator": "=~", "value": "/^$array$/" }
     ]
    }
   ]
  },
  {
   "title": "Kb's Write",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_port",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "port" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Port",
     "select": [
      [
       { "params": [ "kb_write" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "S/N", "operator": "=~", "value": "/^$array$/" }
     ]
    }
   ]
  },
  { "title": "Host Volumes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "IO's per Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_lun_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "lun_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Volume",
     "select": [
      [
       { "params": [ "io_per_second" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "$host" }
     ]
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_lun_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "lun_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Volume",
     "select": [
      [
       { "params": [ "svt_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "$host" }
     ]
    }
   ]
  },
  {
   "title": "Kb's per Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_lun_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "lun_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Volume",
     "select": [
      [
       { "params": [ "kb_per_second" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "$host" }
     ]
    }
   ]
  },
  {
   "title": "IO's size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_lun_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "lun_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Volume",
     "select": [
      [
       { "params": [ "io_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "$host" }
     ]
    }
   ]
  }
 ]
}